spring.application.name=borrow-book
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_book?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Codegym@2025
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.file.name=E:/CODEGYM/bai_tap_code_gym/module_4/ss9_aop_exception_handle/bai_tap/borrow-book/src/main/java/org/example/borrowbook/logs/audit.txt
# (Tùy ch?n) M?c ?? log
logging.level.org.example.borrowbook.aspect=INFO
logging.level.root=INFO